on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # allow manual

jobs:
  sync:
    name: Sync SensEdu
    runs-on: ubuntu-latest
    steps:
      - name: Sync Original Folder
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git checkout master
        
          git remote add upstream https://github.com/ShiegeChan/SensEdu.git
          git fetch upstream

          git checkout upstream/main -- libraries/SensEdu
          cp -r -f libraries/SensEdu/* ./
          rm -r libraries

          git add .
          git commit -m "Sync: Update from original repo libraries/SensEdu"
          git push origin master
